### ISSUE TITLE
Feature suggestion: expm1(x) = exp(x) - 1

### ISSUE THREAD

**Issue by bhbr** [AndreasMadsen/mathfn#1]
log1p(x) is a good idea! I have once encountered the same problem with its inverse function: wanting to compute exp(x) – 1 for small x usually gives 1.00000... – 1, losing significant digits. An implementation of exp(x) – 1 as e. g. sum_(n >= 1) x^n/n! would be very helpful to physicists working in quantum physics or statistical mechanics.

Cheers
Ben

**Comment by AndreasMadsen** [comment]
Sounds very reasonable, I can see that numpy has a [expm1](https://docs.scipy.org/doc/numpy/reference/generated/numpy.expm1.html) function. Would you like to make a pull request?

edit: John D Cook also has an implementation: https://www.johndcook.com/blog/cpp_expm1/ , as you suggested it is a simple taylor approximation.

**Comment by bhbr** [comment]
Oh, I missed the numpy feature (wasn't using Python anyway back then). Just stumbled upon your project and saw log1p. Then the request is of course moot.

**Comment by AndreasMadsen** [comment]
Well, this is JavaScript, so unfortunately numpy isn't much help.

**Comment by AndreasMadsen** [comment]
This feature exists in `cephes` which is the recommended replacement for this module. https://github.com/nearform/node-cephes/#double--cephesexpm1x-double
