### ISSUE TITLE
Incomplete Beta function is actually regularized Beta function

### ISSUE THREAD

**Issue by jlherren** [AndreasMadsen/mathfn#2]
`incBeta(x, a, b)` does not compute the incomplete Beta function, but instead if computes the regularized incomplete Beta, which is not the same. This should be made more clear in the docs and it would be nice to have the real Beta function available as well.

As a workaround one can use `incBeta(x, a, b) * beta(a, b)` to obtain the real incomplete Beta function.

Reference: https://en.wikipedia.org/wiki/Beta_function

**Comment by AndreasMadsen** [comment]
Hmm, I will give it a quick look. But implementing these functions are pretty annoying.

I have recently ported them all to JS using cephes, I think you will find https://github.com/nearform/node-cephes#double--cephesincbetaa-double-bb-double-xx-double to be more complete (not in the mathematical sense :p), faster, and more accurate.

**Comment by AndreasMadsen** [comment]
Should be fixed now, using the workaround you suggested. I also deprecated mathfn suggesting to use node-cephes instead.
