### ISSUE TITLE
`betaln()` is missing?

### ISSUE THREAD

**Issue by rajatkumar** [AndreasMadsen/mathfn#3]
https://github.com/AndreasMadsen/mathfn/blob/66004a96c260a451af7f99551534227fa1303bfa/functions/beta.js#L43
This line refers to `gammaCollection.betaln(x, y)` but looks like `betaln()` is not defined in `gamma.js`

**Comment by AndreasMadsen** [comment]
I would suggest using https://github.com/nearform/node-cephes instead. It is much better in pretty much all aspects.

**Comment by rajatkumar** [comment]
👍
